---
- name: "breaking-change"
  color: ee0701
  description: "A change that changes the API or breaks backward compatibility for users"
- name: "bugfix"
  color: ee0701
  description: "Inconsistencies or issues which will cause a problem for users or implementors"
- name: "documentation"
  color: 0052cc
  description: "Improvements or additions to documentation"
- name: "refactor"
  color: 1d76db
  description: "Updating the code with simpler, easier to understand or more efficient syntax or methods, but not introducing new features"
- name: "performance"
  color: 1d76db
  description: "Improving performance of the project, not introducing new features"
- name: "new-feature"
  color: 0e8a16
  description: "New features or options"
- name: "maintenance"
  color: 2af79e
  description: "Generic maintenance tasks"
- name: "ci"
  color: 1d76db
  description: "Work that improves the continuous integration"

# Status
- name: "in-progress"
  color: fbca04
  description: "Issue is currently being worked on by a developer"
- name: "stale"
  color: fef2c0
  description: "No activity for quite some time"
- name: "no-stale"
  color: fef2c0
  description: "This is exempt from the stale bot"

- name: "security"
  color: ee0701
  description: "Addressing a vulnerability or security risk in this project"

- name: "priority-critical"
  color: ee0701
  description: "Must be addressed as soon as possible"
- name: "priority-high"
  color: b60205
  description: "After critical issues are fixed, these should be dealt with before any further issues"
- name: "priority-medium"
  color: 0e8a16
  description: "This issue may be useful, and needs some attention"
- name: "priority-low"
  color: e4ea8a
  description: "Nice addition, maybe someday"

# SemVer
- name: "major"
  color: b60205
  description: "This PR causes a major bump in the version number"
- name: "minor"
  color: 0e8a16
  description: "This PR causes a minor bump in the version number"

# Release Please
- name: "autorelease: pending"
  color: "#ededed"
- name: "autorelease: tagged"
  color: "#ededed"

# Github Default
- name: bug
  color: d73a4a
  description: Something isn't working
- name: "dependencies"
  description: "Pull requests that update a dependency file"
  color: 0366d6
- name: "documentation"
  color: 0052cc
  description: "Improvements or additions to documentation"
- name: "enhancement"
  color: a2eeef
  description: "New feature or request"
- name: "duplicate"
  color: cfd3d7
  description: "This issue or pull request already exists"
- name: "good first issue"
  color: 7057ff
  description: "Good for newcomers"
- name: "help wanted"
  color: 7057ff
  description: "Good for newcomers"
- name: "invalid"
  color: e4e669
  description: "This doesn't seem right"
- name: "question"
  color: d876e3
  description: Further information is requested

# Language
- name: "go"
  color: 16e2e2
  description: "Pull requests that update Go code"
- name: "javascript"
  color: 168700
  description: "Pull requests that update javascript code"
